:concurrency: 2
:logfile: ./log/sidekiq.log
:queues:
  - default
:schedule:
  find_overdue_subscriptions:
    every: '45m'
    queue: default
    class: FindOverdueSubscriptionsJob
    description: 'This job finds all active overdue subscriptions and creates a sidekiq job to charge the subscriber'
